### ISSUE TITLE
Translated "Experiments with AMSGrad" to Chinese.

### ISSUE THREAD

**Issue by weakish** [fdlm/amsgrad_experiments#1]
Hi, I've translated your article [Experiments with AMSGrad][0] to [Chinese][1].
Credit is given at the beginning (in translator's note),
and there is also an attribution and a back link at the end.
I hope this complies the conditions of CC-By.
If you see anything improper, or have any other requirements/suggestions,
please let me know.

Thanks.

[0]: https://fdlm.github.io/post/amsgrad/
[1]: https://www.jqr.com/article/000169

**Comment by fdlm** [comment]
Awesome, thanks! :+1:
